"""Conductance-based double-exponential synapses for bgnet.

Each synapse type (AMPA, GABA_A) is described by a peak conductance g_max
in mS/cm^2 (absolute, optimizer-controlled), a reversal potential E_syn, a
rise time tau_rise, a decay time tau_decay, and a fixed transmission delay.

The conductance time course of a single presynaptic spike at t=0 is

    g(t) = (g_max / norm) * (exp(-t/tau_decay) - exp(-t/tau_rise)),  t > 0

where ``norm`` is the analytical peak of (exp(-t/tau_decay) - exp(-t/tau_rise))
that occurs at

    t_peak = (tau_rise * tau_decay / (tau_decay - tau_rise))
             * log(tau_decay / tau_rise)

so that g_max is exactly the peak conductance generated by one spike.

State representation. For each pathway, two per-postsynaptic state variables
(x, y) accumulate decaying contributions from arriving presynaptic spikes:

    dx/dt = -x/tau_decay + sum_pre(g_max * connection * spike_arriving)
    dy/dt = -y/tau_rise  + sum_pre(g_max * connection * spike_arriving)

The synaptic conductance and current are then

    g_syn = (x - y) / norm
    I_syn = g_syn * (V_post - E_syn)

The HH sign convention (positive I_syn = current OUT, hyperpolarizing) is
used so that the membrane equation is uniformly

    C_m dV/dt = -I_ion - I_syn + I_drive + I_noise + I_app

across all neuron types. AGENTS.md step 4 writes the synaptic current as
I_syn = g * (E - V), which is the depolarizing-positive convention; that
form requires +I_syn in the membrane eq. The forms are equivalent up to a
sign; this module commits to the (V - E) form to match neurons/stn.py and
neurons/pallidum.py and to avoid the per-population sign mismatch that
plagued the legacy integrator.

Delay handling lives in the integrator: this module provides per-step
state updates given the spike pulse already arriving at each postsynaptic
neuron this timestep.

Sources for default time constants and reversal potentials:
    Rubin & Terman 2004, J Comput Neurosci 16(3):211-235
    Destexhe et al. 1994, J Comput Neurosci 1(3):195-230
"""
from __future__ import annotations

from typing import NamedTuple

import jax.numpy as jnp


class SynapseParams(NamedTuple):
    """Parameters for one synapse type."""
    tau_rise_ms: float
    tau_decay_ms: float
    E_syn: float        # mV
    delay_ms: float


def ampa_params(delay_ms: float = 5.0) -> SynapseParams:
    """Excitatory AMPA synapse (E = 0 mV, fast double-exponential)."""
    return SynapseParams(tau_rise_ms=1.0, tau_decay_ms=3.0,
                         E_syn=0.0, delay_ms=delay_ms)


def gaba_a_params(delay_ms: float = 5.0) -> SynapseParams:
    """Inhibitory GABA_A synapse (E = -70 mV)."""
    return SynapseParams(tau_rise_ms=5.0, tau_decay_ms=8.0,
                         E_syn=-70.0, delay_ms=delay_ms)


def peak_normalization(tau_rise: float, tau_decay: float) -> float:
    """Return the analytical peak value of (exp(-t/tau_decay) - exp(-t/tau_rise))
    starting from a unit unit-impulse spike at t = 0+.

    Used to normalize so that g_max equals the peak conductance per spike.
    """
    if tau_rise >= tau_decay:
        raise ValueError("tau_rise must be smaller than tau_decay for double-exponential synapse.")
    t_peak = (tau_rise * tau_decay / (tau_decay - tau_rise)) * jnp.log(tau_decay / tau_rise)
    peak = jnp.exp(-t_peak / tau_decay) - jnp.exp(-t_peak / tau_rise)
    return float(peak)


def init_state(n_post: int) -> tuple[jnp.ndarray, jnp.ndarray]:
    """Zero-initialize per-postsynaptic (x, y) state for one pathway."""
    return jnp.zeros((n_post,)), jnp.zeros((n_post,))


def synapse_step(x: jnp.ndarray, y: jnp.ndarray,
                 conductance_pulse: jnp.ndarray,
                 dt: float, p: SynapseParams) -> tuple[jnp.ndarray, jnp.ndarray]:
    """Advance synapse state by one timestep.

    Parameters
    ----------
    x, y : (N_post,) arrays
        Current decay/rise state variables.
    conductance_pulse : (N_post,) array
        Sum over the postsynaptic neuron's presynaptic partners of
        ``g_max * (spike that arrives this step)``. Computed by the
        integrator after applying the synaptic delay to presynaptic spikes.
    dt : float
        Integration timestep (ms).
    p : SynapseParams
    """
    decay_d = jnp.exp(-dt / p.tau_decay_ms)
    decay_r = jnp.exp(-dt / p.tau_rise_ms)
    x_new = x * decay_d + conductance_pulse
    y_new = y * decay_r + conductance_pulse
    return x_new, y_new


def synaptic_current(x: jnp.ndarray, y: jnp.ndarray,
                     V_post: jnp.ndarray, p: SynapseParams,
                     norm: float) -> jnp.ndarray:
    """HH sign convention: positive I_syn = current OUT of the cell.

    The caller is expected to pass the peak normalization computed once at
    network-build time (from ``peak_normalization`` above).
    """
    g_syn = (x - y) / norm
    return g_syn * (V_post - p.E_syn)
